#!/bin/sh
exec /usr/bin/python3 -I -S -c 'import runpy, sys; sys.path[0:0] = ["/usr/lib/astral-project/python", "/usr/lib/python3/dist-packages"]; runpy.run_module("astral_project.broker.main", run_name="__main__")' --socket-activation
